// Loading
export const GET_ANONYMOUS_CART_ID_LOADING = 'GET_ANONYMOUS_CART_ID_LOADING'
export const GET_CART_DETAILS_LOADING = 'GET_CART_DETAILS_LOADING'

// Success
export const GET_ANONYMOUS_CART_ID_SUCCESS = 'GET_ANONYMOUS_CART_ID_SUCCESS'
export const GET_CART_DETAILS_SUCCESS = 'GET_CART_DETAILS_SUCCESS'

// Failure
export const GET_ANONYMOUS_CART_ID_FAILURE = 'GET_ANONYMOUS_CART_ID_FAILURE'
export const GET_CART_DETAILS_FAILURE = 'GET_CART_DETAILS_FAILURE'
