// Loading
export const GET_ANONYMOUS_CART_ID_LOADING = 'GET_ANONYMOUS_CART_ID_LOADING'
export const GET_CART_DETAILS_LOADING = 'GET_CART_DETAILS_LOADING'
export const DECREMENT_CART_ITEM_LOADING = 'DECREMENT_CART_ITEM_LOADING'
export const INCREMENT_CART_ITEM_LOADING = 'INCREMENT_CART_ITEM_LOADING'
export const DELETE_CART_ITEM_LOADING = 'DELETE_CART_ITEM_LOADING'
export const SAVE_PATIENT_TO_CART_LOADING = 'SAVE_PATIENT_TO_CART_LOADING'
export const SAVE_DELIVERY_ADDRESS_TO_CART_LOADING =
  'SAVE_DELIVERY_ADDRESS_TO_CART_LOADING'
export const UPLOAD_PRESCRIPTION_LOADING = 'UPLOAD_PRESCRIPTION_LOADING'
export const DELETE_PRESCRIPTION_LOADING = 'DELETE_PRESCRIPTION_LOADING'
export const SUBMIT_ORDER_LOADING = 'SUBMIT_ORDER_LOADING'

// Success
export const GET_ANONYMOUS_CART_ID_SUCCESS = 'GET_ANONYMOUS_CART_ID_SUCCESS'
export const GET_CART_DETAILS_SUCCESS = 'GET_CART_DETAILS_SUCCESS'
export const PUT_CART_ITEM_SUCCESS = 'PUT_CART_ITEM_SUCCESS'
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS'
export const SAVE_PATIENT_TO_CART_SUCCESS = 'SAVE_PATIENT_TO_CART_SUCCESS'
export const SAVE_DELIVERY_ADDRESS_TO_CART_SUCCESS =
  'SAVE_DELIVERY_ADDRESS_TO_CART_SUCCESS'
export const UPLOAD_PRESCRIPTION_SUCCESS = 'UPLOAD_PRESCRIPTION_SUCCESS'
export const DELETE_PRESCRIPTION_SUCCESS = 'DELETE_PRESCRIPTION_SUCCESS'
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS'

// Failure
export const GET_ANONYMOUS_CART_ID_FAILURE = 'GET_ANONYMOUS_CART_ID_FAILURE'
export const GET_CART_DETAILS_FAILURE = 'GET_CART_DETAILS_FAILURE'
export const PUT_CART_ITEM_FAILURE = 'PUT_CART_ITEM_FAILURE'
export const DELETE_CART_ITEM_FAILURE = 'DELETE_CART_ITEM_FAILURE'
export const SAVE_PATIENT_TO_CART_FAILURE = 'SAVE_PATIENT_TO_CART_FAILURE'
export const SAVE_DELIVERY_ADDRESS_TO_CART_FAILURE =
  'SAVE_DELIVERY_ADDRESS_TO_CART_FAILURE'
export const UPLOAD_PRESCRIPTION_FAILURE = 'UPLOAD_PRESCRIPTION_FAILURE'
export const DELETE_PRESCRIPTION_FAILURE = 'DELETE_PRESCRIPTION_FAILURE'
export const SUBMIT_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE'

// transfer cart
export const CART_TRANSFER_LOADING = 'CART_TRANSFER_LOADING'
export const CART_TRANSFER_SUCCESS = 'CART_TRANSFER_SUCCESS'
export const CART_TRANSFER_FAILURE = 'CART_TRANSFER_FAILURE'

export const UPDATE_IS_CART_OPEN_LOGIN_FLAG = 'UPDATE_IS_CART_OPEN_LOGIN_FLAG'
export const UPDATE_IS_CART_OPEN_REGISTER_MODAL_FLAG =
  'UPDATE_IS_CART_OPEN_REGISTER_MODAL_FLAG'
export const RESET_CART_STATE = 'RESET_CART_STATE'

export const GO_TO_CART_SNACKBAR = 'GO_TO_CART_SNACKBAR'

// to apply coupon Code
export const SUBMIT_COUPON_CODE_LOADING = 'SUBMIT_COUPON_CODE_LOADING'
export const SUBMIT_COUPON_CODE_SUCCESS = 'SUBMIT_COUPON_CODE_SUCCESS'
export const SUBMIT_COUPON_CODE_FAILURE = 'SUBMIT_COUPON_CODE_FAILURE'
export const UPDATE_COUPON_CODE_VALUE = 'UPDATE_COUPON_CODE_VALUE'

// to opt for doctor callback
export const OPT_DOCTOR_CALLBACK_LOADING = 'OPT_DOCTOR_CALLBACK_LOADING'
export const OPT_DOCTOR_CALLBACK_SUCCESS = 'OPT_DOCTOR_CALLBACK_SUCCESS'
export const OPT_DOCTOR_CALLBACK_FAILURE = 'OPT_DOCTOR_CALLBACK_FAILURE'

// to opt for express delivery
export const OPT_EXPRESS_DELIVERY_LOADING = 'OPT_EXPRESS_DELIVERY_LOADING'
export const OPT_EXPRESS_DELIVERY_SUCCESS = 'OPT_EXPRESS_DELIVERY_SUCCESS'
export const OPT_EXPRESS_DELIVERY_FAILURE = 'OPT_EXPRESS_DELIVERY_FAILURE'

export const RESET_SUBMIT_ORDER_CART_STATE = 'RESET_SUBMIT_ORDER_CART_STATE'
export const IS_CART_INVALID = 'IS_CART_INVALID'

export const RESET_COUPON_STATE = 'RESET_COUPON_STATE'
// Reset
export const RESET_UPLOAD_PRESCRIPTION_ERROR = 'RESET_UPLOAD_PRESCRIPTION_ERROR'
export const RESET_SAVE_PATIENT_TO_CART_ERROR = 'RESET_SAVE_PATIENT_TO_CART_ERROR'
export const RESET_SAVE_DELIVERY_ADDRESS_TO_CART_ERROR = 'RESET_SAVE_DELIVERY_ADDRESS_TO_CART_ERROR'
