export const GET_ANONYMOUS_CART_ID_LOADING = 'GET_ANONYMOUS_CART_ID_LOADING'
export const GET_ANONYMOUS_CART_ID_SUCCESS = 'GET_ANONYMOUS_CART_ID_SUCCESS'
export const GET_ANONYMOUS_CART_ID_FAILURE = 'GET_ANONYMOUS_CART_ID_FAILURE'
