export const GET_RELATED_MEDICINES_LOADING = 'GET_RELATED_MEDICINES_LOADING'
export const GET_RELATED_MEDICINES_SUCCESS = 'GET_RELATED_MEDICINES_SUCCESS'
export const GET_RELATED_MEDICINES_FAILURE = 'GET_RELATED_MEDICINES_FAILURE'
