export const GET_MOLECULE_SUMMARY_LOADING = 'GET_MOLECULE_SUMMARY_LOADING'
export const GET_MOLECULE_SUMMARY_SUCCESS = 'GET_MOLECULE_SUMMARY_SUCCESS'
export const GET_MOLECULE_SUMMARY_FAILURE = 'GET_MOLECULE_SUMMARY_FAILURE'
