export const GET_PRODUCT_DETAILS_LOADING = 'GET_PRODUCT_DETAILS_LOADING'
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAILURE = 'GET_PRODUCT_DETAILS_FAILURE'

// export const GET_PRODUCT_DETAILS_SUMMARY_LOADING = 'GET_PRODUCT_DETAILS_SUMMARY_LOADING'
// export const GET_PRODUCT_DETAILS_SUMMARY_SUCCESS = 'GET_PRODUCT_DETAILS_SUMMARY_SUCCESS'
// export const GET_PRODUCT_DETAILS_SUMMARY_FAILURE = 'GET_PRODUCT_DETAILS_SUMMARY_FAILURE'
