export const GET_PRODUCT_DETAILS_LOADING = 'GET_PRODUCT_DETAILS_LOADING'
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAILURE = 'GET_PRODUCT_DETAILS_FAILURE'
