export const CUSTOMER_REGISTER_LOADING = 'CUSTOMER_REGISTER_LOADING'
export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSTOMER_REGISTER_FAILURE = 'CUSTOMER_REGISTER_FAILURE'
