export const GET_PAST_MEDICINES_LOADING = 'GET_PAST_MEDICINES_LOADING'
export const GET_PAST_MEDICINES_SUCCESS = 'GET_PAST_MEDICINES_SUCCESS'
export const GET_PAST_MEDICINES_FAILURE = 'GET_PAST_MEDICINES_FAILURE'

export const UPDATE_REFILL_PATIENT_DETAILS = 'UPDATE_REFILL_PATIENT_DETAILS'
