export const CHECK_PINCODE_LOADING = 'CHECK_PINCODE_LOADING'
export const CHECK_PINCODE_SUCCESS = 'CHECK_PINCODE_SUCCESS'
export const CHECK_PINCODE_FAILURE = 'CHECK_PINCODE_FAILURE'
export const HANDLE_PINCODE_DIALOG = 'HANDLE_PINCODE_DIALOG'
