// loading state of delivery details
export const GET_DELIVERY_DETAILS_LIST_LOADING = 'GET_DELIVERY_DETAILS_LIST_LOADING'

// success state of delivery details
export const GET_DELIVERY_DETAILS_LIST_SUCCESS = 'GET_DELIVERY_DETAILS_LIST_SUCCESS'

// error state of delivery details
export const GET_DELIVERY_DETAILS_LIST_FAILURE = 'GET_DELIVERY_DETAILS_LIST_FAILURE'

// save selected addressId
export const SAVE_ADDRESS_SELECTED = 'SAVE_ADDRESS_SELECTED'

export const SUBMIT_DELIVERY_DETAILS_LOADING = 'SUBMIT_DELIVERY_DETAILS_LOADING'

export const SUBMIT_DELIVERY_DETAILS_SUCCESS = 'SUBMIT_DELIVERY_DETAILS_SUCCESS'

export const SUBMIT_DELIVERY_DETAILS_FAILURE = 'SUBMIT_DELIVERY_DETAILS_SUCCESS'

// pincode check pincode details
export const CHECK_PINCODE_DETAIL_LOADING = 'CHECK_PINCODE_DETAIL_LOADING'

export const CHECK_PINCODE_DETAIL_SUCCESS = 'CHECK_PINCODE_DETAIL_SUCCESS'

export const CHECK_PINCODE_DETAIL_FAILURE = 'CHECK_PINCODE_DETAIL_FAILURE'

// update address form values
export const UPDATE_ADDRESS_FORM_VALUE = 'UPDATE_ADDRESS_FORM_VALUE'
