// Loading
export const GET_DELIVERY_DETAILS_LIST_LOADING = 'GET_DELIVERY_DETAILS_LIST_LOADING'

// Success
export const GET_DELIVERY_DETAILS_LIST_SUCCESS = 'GET_DELIVERY_DETAILS_LIST_SUCCESS'

// Failure
export const GET_DELIVERY_DETAILS_LIST_FAILURE = 'GET_DELIVERY_DETAILS_LIST_FAILURE'
