export const SEND_OTP_LOADING = 'SEND_OTP_LOADING'

export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'

export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE'

export const OTP_VERIFIED_LOADING = 'OTP_VERIFIED_LOADING'

export const OTP_VERIFIED_SUCCESS = 'OTP_VERIFIED_SUCCESS'

export const OTP_VERIFIED_FAILURE = 'OTP_VERIFIED_FAILURE'

export const TOGGLE_AUTHENTICATION = 'TOGGLE_AUTHENTICATION'

export const RESET_IS_NEW_USER_FLAG = 'RESET_IS_NEW_USER_FLAG'

export const HANDLE_SESSION_EXPIRATION = 'HANDLE_SESSION_EXPIRATION'
