// Loading
export const GET_PATIENT_DETAILS_LIST_LOADING = 'GET_PATIENT_DETAILS_LIST_LOADING'

// Success
export const GET_PATIENT_DETAILS_LIST_SUCCESS = 'GET_PATIENT_DETAILS_LIST_SUCCESS'

// Failure
export const GET_PATIENT_DETAILS_LIST_FAILURE = 'GET_PATIENT_DETAILS_LIST_FAILURE'

export const SAVE_PATIENT_SELECTED = 'SAVE_PATIENT_SELECTED'
