export const SNACK_BAR_DURATION = 6000
export const SNACK_BAR_DURATION_3000 = 3000
export const DELIVERY_OPTION_URGENT = 'URGENT'
export const DELIVERY_OPTION_NORMAL = 'NORMAL'
export const LF_ASSURED = 'LF_ASSURED'

export const URGENT_DELIVERY = 'URGENT_DELIVERY'

export const IN_STOCK = 'IN_STOCK'

export const NORMAL = 'NORMAL'
