export const SNACK_BAR_DURATION = 6000
export const DELIVERY_OPTION_URGENT = 'URGENT'
export const DELIVERY_OPTION_NORMAL = 'NORMAL'
export const LF_ASSURED = 'LF_ASSURED'
export const NORMAL = 'NORMAL'
