// get order details
export const GET_ORDER_DETAILS_LOADING = 'GET_ORDER_DETAILS_LOADING'
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE'
