// get order details
export const GET_ORDER_DETAILS_LOADING = 'GET_ORDER_DETAILS_LOADING'
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE'

// get payment channels
export const GET_PAYMENT_CHANNELS_LOADING = 'GET_PAYMENT_CHANNELS_LOADING'
export const GET_PAYMENT_CHANNELS_SUCCESS = 'GET_PAYMENT_CHANNELS_SUCCESS'
export const GET_PAYMENT_CHANNELS_FAILURE = 'GET_PAYMENT_CHANNELS_FAILURE'
