export const SEARCH_MEDICINE_LOADING = 'SEARCH_MEDICINE_LOADING'
export const SEARCH_MEDICINE_SUCCESS = 'SEARCH_MEDICINE_SUCCESS'
export const SEARCH_MEDICINE_FAILURE = 'SEARCH_MEDICINE_FAILURE'
export const UPDATE_INPROGRESS_MEDICINE_STATE = 'UPDATE_INPROGRESS_MEDICINE_STATE'
