export const SEARCH_MEDICINE_LOADING = 'SEARCH_MEDICINE_LOADING'
export const SEARCH_MEDICINE_SUCCESS = 'SEARCH_MEDICINE_SUCCESS'
export const SEARCH_MEDICINE_FAILURE = 'SEARCH_MEDICINE_FAILURE'
export const RESET_SEARCH_MEDICINE_STATE = 'RESET_SEARCH_MEDICINE_STATE'
